name: Deploy to AWS S3

on:
  push:
    branches:
      - master  # 修改为您实际使用的分支名（main或master）
    paths:
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'
      - '**/*.jpg'
      - '**/*.png'
      - '**/*.svg'
      - '**/*.ico'
  
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 1200
      
      - name: Upload frontend to S3
        run: |
          # 上传HTML、CSS和JavaScript文件
          aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} \
            --exclude "*" \
            --include "*.html" \
            --include "static/**/*.css" \
            --include "static/**/*.js" \
            --include "static/**/*.jpg" \
            --include "static/**/*.png" \
            --include "static/**/*.svg" \
            --include "static/**/*.ico" \
            --delete
      
      - name: Invalidate CloudFront cache
        run: |
          # 获取CloudFront分配ID
          if [ -n "${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}" ]; then
            # 如果已经提供了分配ID，直接使用
            aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
            echo "已创建CloudFront缓存失效"
          else
            # 尝试使用域名查找分配ID
            DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items!=null] | [?contains(Aliases.Items, '${{ secrets.DOMAIN_NAME }}')].Id" --output text)
            
            if [ -n "$DISTRIBUTION_ID" ]; then
              # 创建缓存失效
              aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
              echo "已创建CloudFront缓存失效，分配ID: $DISTRIBUTION_ID"
            else
              echo "警告：未找到匹配的CloudFront分配，跳过缓存失效步骤"
            fi
          fi