name: Deploy to AWS S3

on:
  push:
    branches:
      - main
    paths:
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'
      - '**/*.jpg'
      - '**/*.png'
      - '**/*.svg'
      - '**/*.ico'
  
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 1200
      
      - name: Upload frontend to S3
        run: |
          # 上传HTML、CSS和JavaScript文件
          aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} \
            --exclude "*" \
            --include "*.html" \
            --include "static/**/*.css" \
            --include "static/**/*.js" \
            --include "static/**/*.jpg" \
            --include "static/**/*.png" \
            --include "static/**/*.svg" \
            --include "static/**/*.ico" \
            --delete
      
      - name: Invalidate CloudFront cache
        run: |
          # 获取CloudFront分配ID
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items!=null] | [?contains(Aliases.Items, '${{ secrets.DOMAIN_NAME }}')].Id" --output text)
          
          if [ -n "$DISTRIBUTION_ID" ]; then
            # 创建缓存失效
            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
            echo "已创建CloudFront缓存失效"
          else
            echo "未找到匹配的CloudFront分配"
          fi 