
name: Deploy static files to AWS S3
on:
  push:
    branches:
      - master  # 当推送到 master 分支时触发
      # - python-refactor  # 当推送到 python-refactor 分支时也触发
    paths:
        - '**/*.html'
        - '**/*.css'
        - '**/*.js'
        - '**/*.jpg'
        - '**/*.png'
        - '**/*.svg'
        - '**/*.ico'
    
  workflow_dispatch:  # 手动触发

permissions:
  id-token: write  # 允许 GitHub OIDC 访问 AWS
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Sync static files to S3
        run: |
          # 上传 static 文件夹到 S3 桶
          # 上传HTML、CSS和JavaScript文件
          aws s3 sync . s3://${{ secrets.AWS_S3_BUCKET }} \
            --exclude "*" \
            --include "*.html" \
            --include "static/**/*.css" \
            --include "static/**/*.js" \
            --include "static/**/*.jpg" \
            --include "static/**/*.png" \
            --include "static/**/*.svg" \
            --include "static/**/*.ico" \
            --delete
          
      - name: Invalidate CloudFront Cache
        run: |
          # 刷新 CloudFront 缓存以使更改立即可见
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
